import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  Award,
  BarChart3,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CheckCircle,
  ChevronRight,
  Clock,
  Cloud,
  Code,
  Cog,
  CreditCard,
  Database,
  DollarSign,
  Edit3,
  Eye,
  FileCheck,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FolderOpen,
  Gauge,
  Globe,
  GraduationCap,
  Grid,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Key,
  Landmark,
  Laptop,
  Layers,
  Layout,
  LayoutGrid,
  LifeBuoy,
  LineChart,
  Link,
  Lock,
  LucideIcon,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Monitor,
  MousePointerClick,
  Network,
  Palette,
  PenTool,
  Phone,
  PieChart,
  PlayCircle,
  Plug,
  Plus,
  Printer,
  Puzzle,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  StickyNote,
  Store,
  Table,
  Tag,
  Target,
  ThumbsUp,
  Timer,
  ToggleLeft,
  TrendingUp,
  Truck,
  Upload,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  UsersRound,
  Wand2,
  Wrench,
  Zap,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-left-right': ArrowLeftRight,
  award: Award,
  'bar-chart-3': BarChart3,
  'book-open': BookOpen,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  calendar: Calendar,
  'check-circle': CheckCircle,
  'chevron-right': ChevronRight,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  cog: Cog,
  'credit-card': CreditCard,
  database: Database,
  'dollar-sign': DollarSign,
  'edit-3': Edit3,
  eye: Eye,
  'file-check': FileCheck,
  'file-text': FileText,
  filter: Filter,
  fingerprint: Fingerprint,
  flag: Flag,
  'folder-open': FolderOpen,
  gauge: Gauge,
  globe: Globe,
  'graduation-cap': GraduationCap,
  grid: Grid,
  headphones: Headphones,
  heart: Heart,
  'help-circle': HelpCircle,
  home: Home,
  image: Image,
  inbox: Inbox,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  layout: Layout,
  'layout-grid': LayoutGrid,
  'life-buoy': LifeBuoy,
  'line-chart': LineChart,
  link: Link,
  lock: Lock,
  mail: Mail,
  map: Map,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  monitor: Monitor,
  'mouse-pointer-click': MousePointerClick,
  network: Network,
  palette: Palette,
  'pen-tool': PenTool,
  phone: Phone,
  'pie-chart': PieChart,
  'play-circle': PlayCircle,
  plug: Plug,
  plus: Plus,
  printer: Printer,
  puzzle: Puzzle,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  'sticky-note': StickyNote,
  store: Store,
  table: Table,
  tag: Tag,
  target: Target,
  'thumbs-up': ThumbsUp,
  timer: Timer,
  'toggle-left': ToggleLeft,
  'trending-up': TrendingUp,
  truck: Truck,
  upload: Upload,
  'user-check': UserCheck,
  'user-cog': UserCog,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  users: Users,
  'users-round': UsersRound,
  'wand-2': Wand2,
  wrench: Wrench,
  zap: Zap,
};

export function resolveIcon(name: string): LucideIcon {
  return iconMap[name] || Sparkles;
}
