export type Priority = 'P0' | 'P1' | 'P2';
export type StepStatus = 'untested' | 'pass' | 'fail' | 'skip';

export interface TestStep {
  id: string;
  description: string;
  priority: Priority;
  notes?: string;
  /** Step-by-step instructions a tester can follow without knowing the app */
  howTo: string[];
  /** Sample data to use during the test (optional) */
  sampleData?: Record<string, string>;
}

export interface TestSection {
  id: string;
  title: string;
  steps: TestStep[];
}

export const testSections: TestSection[] = [
  {
    id: 'auth',
    title: 'Auth & Onboarding',
    steps: [
      {
        id: 'auth-1',
        description: 'Sign up with email/password creates account and redirects to onboarding',
        priority: 'P0',
        howTo: [
          'Open the app in an incognito/private browser window',
          'Click "Sign Up" or navigate to /signup',
          'Enter the test email and password shown below',
          'Click "Create Account"',
          'Check that you are redirected to the onboarding wizard (not the dashboard)',
          'Verify the onboarding asks for org name, industry, and team size',
        ],
        sampleData: {
          Email: 'qa-tester-{timestamp}@test.siggly.com',
          Password: 'TestPass123!',
          'Tip': 'Replace {timestamp} with current time, e.g. qa-tester-1709500000@test.siggly.com',
        },
      },
      {
        id: 'auth-2',
        description: 'Sign up with Google OAuth creates account and redirects to onboarding',
        priority: 'P0',
        howTo: [
          'Open the app in an incognito/private browser window',
          'Click "Sign Up" then click "Continue with Google"',
          'Sign in with a Google account that has NOT been used with Siggly before',
          'After Google auth completes, verify you land on the onboarding wizard',
          'Confirm your Google email/name are pre-filled where applicable',
        ],
        sampleData: {
          'Google Account': 'Use a personal Google account not already linked to Siggly',
        },
      },
      {
        id: 'auth-3',
        description: 'Sign up with Microsoft OAuth creates account and redirects to onboarding',
        priority: 'P0',
        howTo: [
          'Open the app in an incognito/private browser window',
          'Click "Sign Up" then click "Continue with Microsoft"',
          'Sign in with a Microsoft account that has NOT been used with Siggly before',
          'After Microsoft auth completes, verify you land on the onboarding wizard',
          'Confirm your Microsoft email/name are pre-filled where applicable',
        ],
        sampleData: {
          'Microsoft Account': 'Use a personal Microsoft/Outlook account not already linked to Siggly',
        },
      },
      {
        id: 'auth-4',
        description: 'Login with valid credentials redirects to dashboard',
        priority: 'P0',
        howTo: [
          'Open the app and navigate to /login',
          'Enter valid test credentials (an account that already exists)',
          'Click "Sign In"',
          'Verify you are redirected to the /dashboard page',
          'Confirm the dashboard loads without errors and shows your org name',
        ],
        sampleData: {
          Email: 'Use an existing test account',
          Password: 'The password you used during signup',
        },
      },
      {
        id: 'auth-5',
        description: 'Login with invalid credentials shows error message',
        priority: 'P0',
        howTo: [
          'Open the app and navigate to /login',
          'Enter a valid email but an incorrect password',
          'Click "Sign In"',
          'Verify an error message appears (e.g. "Invalid login credentials")',
          'Confirm you are NOT redirected — you stay on the login page',
          'Try a completely non-existent email and verify the same error appears (no user enumeration)',
        ],
        sampleData: {
          Email: 'existing-user@test.siggly.com',
          'Wrong Password': 'WrongPassword999!',
          'Non-existent Email': 'nobody-here-12345@test.siggly.com',
        },
      },
      {
        id: 'auth-6',
        description: 'Password reset flow sends email and allows password change',
        priority: 'P0',
        howTo: [
          'Navigate to /login and click "Forgot password?"',
          'Enter the email of an existing test account',
          'Click "Send Reset Link"',
          'Check the inbox for a password reset email (check spam if needed)',
          'Click the reset link in the email',
          'Enter a new password and confirm it',
          'Submit the form and verify a success message appears',
          'Log in with the new password to confirm it works',
        ],
        sampleData: {
          Email: 'Use an existing test account you have inbox access to',
          'New Password': 'NewTestPass456!',
        },
      },
      {
        id: 'auth-7',
        description: 'Onboarding wizard completes all steps (org name, industry, team size)',
        priority: 'P0',
        howTo: [
          'After signing up with a new account, you should be on the onboarding wizard',
          'Step 1 — Enter an organization name',
          'Step 2 — Select an industry from the dropdown',
          'Step 3 — Select a team size range',
          'Click "Continue" / "Next" through each step',
          'After the final step, verify you are redirected to the dashboard',
          'Confirm the org name appears in the sidebar/header',
        ],
        sampleData: {
          'Organization Name': 'QA Test Company',
          Industry: 'Technology',
          'Team Size': '11-50',
        },
      },
      {
        id: 'auth-8',
        description: 'Invite link creates user account with correct org and role',
        priority: 'P1',
        howTo: [
          'Log in as an admin/owner of a test organization',
          'Go to the Team page (/team)',
          'Click "Invite Member" and enter the test email below',
          'Set role to "Member" and send the invite',
          'Open the invite email in another browser/incognito window',
          'Click the invite link and complete account setup',
          'Verify the new user is in the same organization as the inviter',
          'Verify the new user has the "Member" role',
        ],
        sampleData: {
          'Invite Email': 'qa-invited-{timestamp}@test.siggly.com',
          Role: 'Member',
        },
      },
    ],
  },
  {
    id: 'signatures',
    title: 'Signature Creation & Editing',
    steps: [
      {
        id: 'sig-1',
        description: 'Create new signature from blank template',
        priority: 'P0',
        howTo: [
          'Log in and go to the Dashboard',
          'Click "New Signature" or navigate to /templates/new',
          'Select the "Blank" or "Start from scratch" option',
          'You should land in the signature editor with empty fields',
          'Verify all field inputs are visible (name, title, phone, email, etc.)',
        ],
      },
      {
        id: 'sig-2',
        description: 'Create signature from a pre-built template',
        priority: 'P0',
        howTo: [
          'Navigate to the Templates page (/templates)',
          'Browse the template gallery — confirm templates display with previews',
          'Click on any template to select it',
          'Verify the signature editor opens with the template layout pre-applied',
          'Confirm fields are pre-positioned according to the template design',
        ],
      },
      {
        id: 'sig-3',
        description: 'Edit signature fields (name, title, phone, email)',
        priority: 'P0',
        howTo: [
          'Open an existing signature or create a new one',
          'Fill in each field with the sample data below',
          'After typing in each field, check the live preview updates in real-time',
          'Verify all fields appear correctly formatted in the preview',
        ],
        sampleData: {
          'Full Name': 'Jane Smith',
          'Job Title': 'Marketing Director',
          Phone: '+1 (555) 123-4567',
          Email: 'jane.smith@testcompany.com',
          Company: 'Test Company Inc.',
          Website: 'https://testcompany.com',
        },
      },
      {
        id: 'sig-4',
        description: 'Upload and display profile photo in signature',
        priority: 'P0',
        howTo: [
          'In the signature editor, find the profile photo section',
          'Click the upload area or "Upload Photo" button',
          'Select a JPG or PNG image (under 2MB recommended)',
          'Wait for the upload to complete',
          'Verify the photo appears in both the editor and the live preview',
          'Check that the photo is properly sized/cropped (not stretched)',
        ],
        sampleData: {
          'Test Image': 'Use any headshot-style photo, JPG or PNG, under 2MB',
        },
      },
      {
        id: 'sig-5',
        description: 'Upload and display company logo in signature',
        priority: 'P0',
        howTo: [
          'In the signature editor, find the company logo section',
          'Click the upload area or "Upload Logo" button',
          'Select a logo image (PNG with transparency works best)',
          'Wait for the upload to complete',
          'Verify the logo appears in the live preview',
          'Check that the logo maintains its aspect ratio',
        ],
        sampleData: {
          'Test Logo': 'Use any company logo PNG, ideally with transparent background',
        },
      },
      {
        id: 'sig-6',
        description: 'Add and edit social media links with icons',
        priority: 'P1',
        howTo: [
          'In the signature editor, find the "Social Links" section',
          'Click "Add Social Link" or the + button',
          'Select a platform (e.g., LinkedIn) from the dropdown',
          'Paste the sample URL below into the URL field',
          'Verify the correct icon appears in the preview',
          'Add a second social link (e.g., Twitter/X) and verify both appear',
        ],
        sampleData: {
          LinkedIn: 'https://linkedin.com/in/janesmith',
          'Twitter/X': 'https://x.com/janesmith',
          GitHub: 'https://github.com/janesmith',
        },
      },
      {
        id: 'sig-7',
        description: 'Add promotional banner/CTA to signature',
        priority: 'P1',
        howTo: [
          'In the signature editor, find the "Banner" or "CTA" section',
          'Upload a banner image or enter CTA text',
          'Set the link URL for the banner/CTA',
          'Verify the banner/CTA appears in the live preview',
          'Check that clicking it in preview would go to the correct URL',
        ],
        sampleData: {
          'CTA Text': 'Join our upcoming webinar!',
          'CTA Link': 'https://testcompany.com/webinar',
          'Banner': 'Use any horizontal banner image (600x100px recommended)',
        },
      },
      {
        id: 'sig-8',
        description: 'Change signature colors and fonts',
        priority: 'P1',
        howTo: [
          'In the signature editor, find the styling/design section',
          'Change the primary text color using the color picker',
          'Change the link color to a different color',
          'If available, change the font family',
          'Verify each change updates the live preview immediately',
          'Save and re-open the signature to confirm changes persist',
        ],
        sampleData: {
          'Primary Color': '#1a1a2e (dark navy)',
          'Link Color': '#e94560 (coral red)',
        },
      },
      {
        id: 'sig-9',
        description: 'Live preview updates in real-time as fields change',
        priority: 'P0',
        howTo: [
          'Open any signature in the editor',
          'Focus on the live preview panel (usually on the right side)',
          'Start typing a name — verify the preview updates character by character',
          'Change the phone number — verify instant update',
          'Upload a photo — verify it appears in preview after upload completes',
          'There should be no noticeable delay between typing and preview updating',
        ],
      },
      {
        id: 'sig-10',
        description: 'Save signature persists all changes correctly',
        priority: 'P0',
        howTo: [
          'Make several edits to a signature (name, title, phone, colors)',
          'Click "Save" or the save button',
          'Wait for the save confirmation (toast or checkmark)',
          'Navigate away from the editor (go to dashboard)',
          'Navigate back to the same signature',
          'Verify ALL changes you made are still present',
        ],
      },
      {
        id: 'sig-11',
        description: 'Duplicate an existing signature creates a copy',
        priority: 'P1',
        howTo: [
          'Go to the Dashboard where your signatures are listed',
          'Find the "..." menu or actions on an existing signature',
          'Click "Duplicate" or "Copy"',
          'Verify a new signature appears in the list with a similar name (e.g., "Copy of ...")',
          'Open the duplicate and verify it has all the same content as the original',
        ],
      },
      {
        id: 'sig-12',
        description: 'Delete signature with confirmation dialog',
        priority: 'P1',
        howTo: [
          'Go to the Dashboard where your signatures are listed',
          'Find the "..." menu or actions on a signature you want to delete',
          'Click "Delete"',
          'A confirmation dialog should appear asking you to confirm',
          'Click "Cancel" first — verify the signature is NOT deleted',
          'Click "Delete" again, then confirm — verify the signature is removed from the list',
        ],
      },
    ],
  },
  {
    id: 'templates',
    title: 'Template Management',
    steps: [
      {
        id: 'tmpl-1',
        description: 'Browse template gallery shows all available templates',
        priority: 'P0',
        howTo: [
          'Navigate to /templates',
          'Verify the gallery loads with template cards/thumbnails',
          'Check that each template shows a preview image and name',
          'Scroll through to ensure multiple templates are available',
          'Verify no broken images or layout issues',
        ],
      },
      {
        id: 'tmpl-2',
        description: 'Preview template before selecting',
        priority: 'P1',
        howTo: [
          'On the templates page, hover over or click a template',
          'Look for a "Preview" button or expanded view',
          'Verify the preview shows a larger/detailed view of the template',
          'Confirm you can close the preview without selecting the template',
        ],
      },
      {
        id: 'tmpl-3',
        description: 'Select template pre-fills signature editor with correct layout',
        priority: 'P0',
        howTo: [
          'On the templates page, click "Use Template" or "Select" on any template',
          'Verify you are taken to the signature editor',
          'Check that the editor layout matches the template you selected',
          'Verify placeholder content or layout structure matches the template preview',
        ],
      },
      {
        id: 'tmpl-4',
        description: 'Organization-level default template applies to new signatures',
        priority: 'P1',
        howTo: [
          'Log in as an admin/owner',
          'Go to Settings or Template Management',
          'Set a default template for the organization',
          'Create a new signature (or have a member create one)',
          'Verify the new signature starts with the default template layout',
        ],
      },
      {
        id: 'tmpl-5',
        description: 'Custom template creation (admin/owner only)',
        priority: 'P1',
        howTo: [
          'Log in as an admin or owner',
          'Navigate to /templates and look for "Create Custom Template" or similar',
          'Design a custom template using the template builder',
          'Save the template and verify it appears in the gallery',
          'Log in as a member and verify they can see but not create templates',
        ],
      },
      {
        id: 'tmpl-6',
        description: 'Template categories filter correctly',
        priority: 'P1',
        howTo: [
          'On the templates page, look for category filters (e.g., Professional, Creative, Minimal)',
          'Select a category filter',
          'Verify only templates in that category are shown',
          'Clear the filter and verify all templates return',
        ],
      },
      {
        id: 'tmpl-7',
        description: 'Industry-specific templates show for matching industries',
        priority: 'P1',
        howTo: [
          'Log in with an account whose org has a specific industry set (e.g., "Technology")',
          'Navigate to /templates',
          'Look for an "Industry" or "Recommended" filter/section',
          'Verify templates tagged for your industry are highlighted or shown first',
        ],
      },
      {
        id: 'tmpl-8',
        description: 'Template responsive preview (desktop/mobile)',
        priority: 'P2',
        howTo: [
          'Open a template preview',
          'Look for a desktop/mobile toggle or responsive preview buttons',
          'Switch between desktop and mobile views',
          'Verify the template layout adjusts appropriately for each view',
        ],
      },
    ],
  },
  {
    id: 'deployment',
    title: 'Signature Deployment',
    steps: [
      {
        id: 'dep-1',
        description: 'Copy signature HTML to clipboard',
        priority: 'P0',
        howTo: [
          'Open a completed signature (one with all fields filled in)',
          'Look for a "Copy HTML" or "Copy Signature" button',
          'Click the copy button',
          'Verify a success toast/notification appears ("Copied to clipboard")',
          'Paste into a text editor or email client to verify HTML was copied',
          'Check that the pasted HTML renders the signature correctly',
        ],
      },
      {
        id: 'dep-2',
        description: 'Deploy signature via Google Workspace integration',
        priority: 'P0',
        howTo: [
          'Prerequisite: Google Workspace must be connected (see Integration section)',
          'Open a signature and click "Deploy" or go to the deployment page',
          'Select "Google Workspace" as the deployment method',
          'Select users to deploy to (or all users)',
          'Click "Deploy" and wait for the process to complete',
          'Verify the deployment status shows success',
          'Check Gmail for the deployed users — the signature should appear in compose',
        ],
        sampleData: {
          'Prerequisite': 'Google Workspace admin account must be connected first',
        },
      },
      {
        id: 'dep-3',
        description: 'Deploy signature via Microsoft 365 integration',
        priority: 'P0',
        howTo: [
          'Prerequisite: Microsoft 365 must be connected (see Integration section)',
          'Open a signature and click "Deploy" or go to the deployment page',
          'Select "Microsoft 365" as the deployment method',
          'Select users to deploy to (or all users)',
          'Click "Deploy" and wait for the process to complete',
          'Verify the deployment status shows success',
          'Check Outlook for the deployed users — the signature should appear',
        ],
        sampleData: {
          'Prerequisite': 'Microsoft 365 admin account must be connected first',
        },
      },
      {
        id: 'dep-4',
        description: 'Bulk deploy signatures to multiple users',
        priority: 'P0',
        howTo: [
          'Go to the deployment page or template assignments',
          'Select multiple users using checkboxes or "Select All"',
          'Click "Deploy to Selected" or equivalent bulk action',
          'Verify the deployment processes all selected users',
          'Check the status shows individual results for each user',
          'Confirm total count matches the number of users you selected',
        ],
      },
      {
        id: 'dep-5',
        description: 'Deployment status shows progress and completion',
        priority: 'P0',
        howTo: [
          'Start a deployment (any method)',
          'Watch the deployment status UI',
          'Verify a progress indicator appears (spinner, progress bar, or percentage)',
          'Wait for completion',
          'Verify the final status shows "Complete" or "Success" with user counts',
        ],
      },
      {
        id: 'dep-6',
        description: 'Failed deployments show error details and allow retry',
        priority: 'P1',
        howTo: [
          'This may require triggering a failure (e.g., disconnecting an integration mid-deploy)',
          'After a deployment fails, check the deployment status/history',
          'Verify failed deployments show an error message explaining what went wrong',
          'Look for a "Retry" button on the failed deployment',
          'If available, click Retry and verify it attempts the deployment again',
        ],
      },
      {
        id: 'dep-7',
        description: 'Deployment history log shows all past deployments',
        priority: 'P1',
        howTo: [
          'Run at least 2-3 deployments first',
          'Navigate to deployment history (may be under Settings or Dashboard)',
          'Verify all past deployments are listed with dates',
          'Check each entry shows: template name, user count, status, and timestamp',
          'Verify entries are sorted by date (newest first)',
        ],
      },
      {
        id: 'dep-8',
        description: 'Schedule deployment for a future date/time',
        priority: 'P1',
        howTo: [
          'Start a new deployment',
          'Look for a "Schedule" option instead of "Deploy Now"',
          'Select a future date and time',
          'Confirm the scheduled deployment',
          'Verify it appears in the deployment list as "Scheduled"',
          'Check that it does NOT deploy immediately',
        ],
      },
      {
        id: 'dep-9',
        description: 'Rollback deployment reverts to previous signature',
        priority: 'P1',
        howTo: [
          'Prerequisite: At least 2 deployments must have been completed',
          'Go to deployment history',
          'Find a past deployment and look for a "Rollback" option',
          'Click rollback and confirm',
          'Verify users\' signatures revert to the previous version',
        ],
      },
      {
        id: 'dep-10',
        description: 'Deployment confirmation email sent to admin',
        priority: 'P2',
        howTo: [
          'Complete a deployment (any method)',
          'Check the admin\'s email inbox',
          'Verify a deployment confirmation email was received',
          'Check that the email includes deployment details (user count, template, status)',
        ],
      },
    ],
  },
  {
    id: 'team',
    title: 'Team & User Management',
    steps: [
      {
        id: 'team-1',
        description: 'Invite team member via email sends invite',
        priority: 'P0',
        howTo: [
          'Log in as an admin or owner',
          'Navigate to /team',
          'Click "Invite Member" or "Add User"',
          'Enter the email address below',
          'Select a role (e.g., "Member")',
          'Click "Send Invite"',
          'Verify a success message appears',
          'Check the invited email\'s inbox for the invite email',
        ],
        sampleData: {
          Email: 'qa-team-invite-{timestamp}@test.siggly.com',
          Role: 'Member',
        },
      },
      {
        id: 'team-2',
        description: 'Assign role (owner, admin, member) to team member',
        priority: 'P0',
        howTo: [
          'Navigate to /team',
          'Find an existing team member in the list',
          'Click on their role badge or the edit/settings icon',
          'Change their role from the dropdown (e.g., Member → Admin)',
          'Save the change',
          'Verify the role updates in the team list',
          'Log in as that user and verify their new permissions',
        ],
      },
      {
        id: 'team-3',
        description: 'Remove team member with confirmation',
        priority: 'P0',
        howTo: [
          'Navigate to /team',
          'Find a team member to remove (use a test account)',
          'Click the "Remove" or trash icon',
          'A confirmation dialog should appear',
          'Click "Cancel" first — verify the user is NOT removed',
          'Click "Remove" again and confirm — verify the user disappears from the list',
        ],
      },
      {
        id: 'team-4',
        description: 'Member can only edit their own signature',
        priority: 'P0',
        howTo: [
          'Log in as a user with the "Member" role',
          'Go to the Dashboard',
          'Verify you can see and edit your OWN signature',
          'Try to access another user\'s signature (via URL or team list)',
          'Verify you get an error or are blocked from editing others\' signatures',
        ],
      },
      {
        id: 'team-5',
        description: 'Admin can edit all team signatures',
        priority: 'P0',
        howTo: [
          'Log in as a user with the "Admin" role',
          'Go to the Dashboard or Team page',
          'Open another team member\'s signature',
          'Verify you CAN edit their fields and save changes',
          'Verify the changes persist when viewed by the team member',
        ],
      },
      {
        id: 'team-6',
        description: 'Bulk import users from CSV',
        priority: 'P1',
        howTo: [
          'Log in as an admin/owner',
          'Navigate to /team and look for "Import" or "Bulk Add"',
          'Download the CSV template if available',
          'Create a CSV with the sample data below (or use the template)',
          'Upload the CSV file',
          'Verify the import preview shows correct data',
          'Confirm the import',
          'Check that all imported users appear in the team list',
        ],
        sampleData: {
          'CSV Format': 'email,first_name,last_name,role',
          'Row 1': 'csv-user1@test.siggly.com,Test,User1,member',
          'Row 2': 'csv-user2@test.siggly.com,Test,User2,member',
          'Row 3': 'csv-user3@test.siggly.com,Test,User3,admin',
        },
      },
      {
        id: 'team-7',
        description: 'Sync users from Google Workspace directory',
        priority: 'P1',
        howTo: [
          'Prerequisite: Google Workspace must be connected',
          'Go to Settings → Integrations or the Team page',
          'Click "Sync from Google Workspace" or equivalent',
          'Verify a list of Google Workspace users appears for import',
          'Select users to sync and confirm',
          'Verify synced users appear in the team list with correct names/emails',
        ],
      },
      {
        id: 'team-8',
        description: 'Sync users from Microsoft 365 directory',
        priority: 'P1',
        howTo: [
          'Prerequisite: Microsoft 365 must be connected',
          'Go to Settings → Integrations or the Team page',
          'Click "Sync from Microsoft 365" or equivalent',
          'Verify a list of Microsoft 365 users appears for import',
          'Select users to sync and confirm',
          'Verify synced users appear in the team list with correct names/emails',
        ],
      },
      {
        id: 'team-9',
        description: 'Team member list shows correct roles and status',
        priority: 'P1',
        howTo: [
          'Navigate to /team',
          'Verify each team member shows: name, email, role badge, and active/inactive status',
          'Cross-reference a few users with what you know about their roles',
          'Check that the owner is clearly identified',
          'Verify the list is paginated or scrollable if many users exist',
        ],
      },
      {
        id: 'team-10',
        description: 'Deactivated users cannot log in',
        priority: 'P1',
        howTo: [
          'Log in as an admin/owner',
          'Go to /team and deactivate a test user account',
          'Open an incognito window and try to log in as that deactivated user',
          'Verify the login fails with an appropriate error message',
          'Re-activate the user and verify they can log in again',
        ],
      },
    ],
  },
  {
    id: 'billing',
    title: 'Billing & Subscriptions',
    steps: [
      {
        id: 'bill-1',
        description: 'Free plan limits enforced (5 users max)',
        priority: 'P0',
        howTo: [
          'Log in as an owner of an org on the Free plan',
          'Navigate to /team',
          'Add users until you reach 5 total team members',
          'Try to invite a 6th user',
          'Verify an error or upgrade prompt appears ("Upgrade to add more users")',
          'Confirm the 6th user is NOT added',
        ],
      },
      {
        id: 'bill-2',
        description: 'Upgrade to Professional plan via Stripe checkout',
        priority: 'P0',
        howTo: [
          'Log in as an owner on the Free plan',
          'Go to Settings → Billing or click an upgrade prompt',
          'Select the "Professional" plan',
          'Click "Upgrade" — you should be redirected to Stripe Checkout',
          'Use the Stripe test card below to complete payment',
          'After payment, verify you are redirected back to Siggly',
          'Confirm your plan now shows "Professional" in Settings → Billing',
        ],
        sampleData: {
          'Card Number': '4242 4242 4242 4242',
          Expiry: '12/34',
          CVC: '123',
          ZIP: '10001',
          'Note': 'This is Stripe\'s test card — no real charge is made',
        },
      },
      {
        id: 'bill-3',
        description: 'Stripe webhook processes payment and activates plan',
        priority: 'P0',
        howTo: [
          'This is verified as part of bill-2 (upgrade flow)',
          'After completing Stripe checkout, check that the plan activates without manual intervention',
          'Verify the subscription status shows "Active"',
          'If you have access to Stripe Dashboard, check that the webhook events were processed successfully',
          'Look for checkout.session.completed and customer.subscription.created events',
        ],
      },
      {
        id: 'bill-4',
        description: 'Downgrade to free plan cancels Stripe subscription',
        priority: 'P0',
        howTo: [
          'Log in as an owner on the Professional plan',
          'Go to Settings → Billing',
          'Click "Downgrade to Free" or "Cancel Subscription"',
          'Confirm the downgrade in the confirmation dialog',
          'Verify the plan changes to "Free"',
          'If you have Stripe Dashboard access, verify the subscription is cancelled',
          'Check that the user limit reverts to 5 (may warn about excess users)',
        ],
      },
      {
        id: 'bill-5',
        description: 'Billing portal link opens Stripe customer portal',
        priority: 'P1',
        howTo: [
          'Log in as an owner on a paid plan',
          'Go to Settings → Billing',
          'Click "Manage Billing" or "Billing Portal"',
          'Verify a new tab/window opens to the Stripe Customer Portal',
          'In the portal, verify you can see invoices, update payment method, and cancel',
        ],
      },
      {
        id: 'bill-6',
        description: 'Per-seat billing updates when team size changes',
        priority: 'P1',
        howTo: [
          'Log in as an owner on the Professional plan',
          'Note the current billing amount in Settings → Billing',
          'Add a new team member via /team',
          'Go back to Settings → Billing',
          'Verify the billing amount or seat count has increased by 1',
          'Remove a team member and verify the count decreases',
        ],
        sampleData: {
          'Per-seat price': '$1.50/user/month',
          'Minimum seats': '10',
        },
      },
      {
        id: 'bill-7',
        description: 'Past-due subscription shows warning banner',
        priority: 'P1',
        howTo: [
          'This is difficult to test without Stripe test clocks or manual intervention',
          'If possible: Use Stripe Dashboard to mark a subscription as "past_due"',
          'Log in as the affected org\'s owner',
          'Verify a warning banner appears on the dashboard ("Payment past due")',
          'Verify the banner includes a link to update payment method',
        ],
      },
      {
        id: 'bill-8',
        description: 'Partner discount coupon applies correctly at checkout',
        priority: 'P1',
        howTo: [
          'During the Stripe checkout flow, look for a "Coupon" or "Promo Code" field',
          'Enter a test coupon code (if one exists in Stripe test mode)',
          'Verify the discount is applied and reflected in the total',
          'Complete the purchase and verify the discounted amount is charged',
        ],
        sampleData: {
          'Note': 'Check Stripe Dashboard for available test coupon codes',
        },
      },
    ],
  },
  {
    id: 'integrations',
    title: 'Integrations',
    steps: [
      {
        id: 'int-1',
        description: 'Connect Google Workspace OAuth flow completes',
        priority: 'P0',
        howTo: [
          'Log in as an admin/owner',
          'Go to Settings → Integrations',
          'Click "Connect" next to Google Workspace',
          'A Google OAuth consent screen should appear',
          'Sign in with a Google Workspace admin account',
          'Grant the requested permissions',
          'Verify you are redirected back and the status shows "Connected"',
        ],
      },
      {
        id: 'int-2',
        description: 'Connect Microsoft 365 OAuth flow completes',
        priority: 'P0',
        howTo: [
          'Log in as an admin/owner',
          'Go to Settings → Integrations',
          'Click "Connect" next to Microsoft 365',
          'A Microsoft OAuth consent screen should appear',
          'Sign in with a Microsoft 365 admin account',
          'Grant the requested permissions',
          'Verify you are redirected back and the status shows "Connected"',
        ],
      },
      {
        id: 'int-3',
        description: 'Disconnect integration removes access tokens',
        priority: 'P0',
        howTo: [
          'Prerequisite: An integration must be connected',
          'Go to Settings → Integrations',
          'Click "Disconnect" next to the connected integration',
          'Confirm the disconnection in the dialog',
          'Verify the status changes to "Not Connected"',
          'Try to deploy via that integration — it should prompt you to reconnect',
        ],
      },
      {
        id: 'int-4',
        description: 'Google Workspace user sync pulls directory users',
        priority: 'P1',
        howTo: [
          'Prerequisite: Google Workspace must be connected',
          'Go to the Team page or Settings → Integrations',
          'Click "Sync Users" from Google Workspace',
          'Verify a list of Google Workspace directory users appears',
          'Select users to import and confirm',
          'Verify imported users appear in the team list with names and emails from Google',
        ],
      },
      {
        id: 'int-5',
        description: 'Microsoft 365 user sync pulls directory users',
        priority: 'P1',
        howTo: [
          'Prerequisite: Microsoft 365 must be connected',
          'Go to the Team page or Settings → Integrations',
          'Click "Sync Users" from Microsoft 365',
          'Verify a list of Microsoft 365 directory users appears',
          'Select users to import and confirm',
          'Verify imported users appear in the team list with names and emails from Microsoft',
        ],
      },
      {
        id: 'int-6',
        description: 'HubSpot integration connects and syncs contacts',
        priority: 'P1',
        howTo: [
          'Log in as an admin/owner',
          'Go to Settings → Integrations',
          'Click "Connect" next to HubSpot',
          'Complete the HubSpot OAuth flow',
          'Verify the status shows "Connected"',
          'Check if contacts sync automatically or click "Sync" if manual',
        ],
      },
      {
        id: 'int-7',
        description: 'Calendly integration adds meeting link to signatures',
        priority: 'P1',
        howTo: [
          'Go to Settings → Integrations and connect Calendly',
          'In the signature editor, look for a "Meeting Link" or "Calendly" option',
          'Enable the Calendly meeting link',
          'Verify the meeting link appears in the signature preview',
          'Click the link in preview to verify it opens the correct Calendly page',
        ],
        sampleData: {
          'Calendly URL': 'https://calendly.com/your-test-account',
        },
      },
      {
        id: 'int-8',
        description: 'Google Calendar integration adds meeting link to signatures',
        priority: 'P1',
        howTo: [
          'Go to Settings → Integrations and connect Google Calendar',
          'In the signature editor, look for a "Meeting Link" or "Google Meet" option',
          'Enable the Google Calendar/Meet link',
          'Verify the meeting link appears in the signature preview',
        ],
      },
      {
        id: 'int-9',
        description: 'Token refresh handles expired OAuth tokens gracefully',
        priority: 'P0',
        howTo: [
          'This tests automatic token refresh (hard to trigger manually)',
          'Connect an integration and wait for the token to expire (usually 1 hour for Google)',
          'Alternatively: If you have DB access, manually expire the token timestamp',
          'Try to perform an action that uses the integration (e.g., deploy or sync)',
          'Verify it succeeds without asking you to reconnect (token auto-refreshed)',
          'Check that no error is shown to the user',
        ],
      },
      {
        id: 'int-10',
        description: 'Integration status page shows connected/disconnected state',
        priority: 'P1',
        howTo: [
          'Navigate to Settings → Integrations',
          'Verify each integration shows a clear "Connected" or "Not Connected" status',
          'Connected integrations should show a green indicator and "Disconnect" button',
          'Disconnected integrations should show a "Connect" button',
          'Verify the connected account email/name is displayed',
        ],
      },
    ],
  },
  {
    id: 'analytics',
    title: 'Analytics & Tracking',
    steps: [
      {
        id: 'ana-1',
        description: 'Analytics dashboard loads with correct date range',
        priority: 'P1',
        howTo: [
          'Navigate to the Analytics page (may be under Dashboard or a dedicated /analytics route)',
          'Verify the page loads without errors',
          'Check the default date range (usually last 30 days)',
          'Change the date range using the date picker',
          'Verify the data updates to reflect the new range',
        ],
      },
      {
        id: 'ana-2',
        description: 'Click tracking records link clicks in signatures',
        priority: 'P1',
        howTo: [
          'Deploy a signature with tracking enabled',
          'Send a test email using that signature',
          'Click a link in the signature (e.g., website URL or social link)',
          'Wait a few minutes for tracking to process',
          'Go to the Analytics page and verify the click is recorded',
          'Check that the click is attributed to the correct signature/link',
        ],
      },
      {
        id: 'ana-3',
        description: 'View tracking records email opens (pixel tracking)',
        priority: 'P1',
        howTo: [
          'Deploy a signature with tracking enabled',
          'Send a test email using that signature',
          'Open the email in a client that loads images (not all clients do)',
          'Wait a few minutes for tracking to process',
          'Go to Analytics and verify an "open" or "view" event is recorded',
        ],
        sampleData: {
          'Note': 'Some email clients block tracking pixels. Test in a client that loads images by default.',
        },
      },
      {
        id: 'ana-4',
        description: 'Analytics breakdown by user shows individual stats',
        priority: 'P2',
        howTo: [
          'Go to the Analytics page',
          'Look for a "By User" tab or breakdown view',
          'Verify each user is listed with their individual click/view counts',
          'Check that totals add up correctly',
        ],
      },
      {
        id: 'ana-5',
        description: 'Analytics breakdown by signature shows per-signature stats',
        priority: 'P2',
        howTo: [
          'Go to the Analytics page',
          'Look for a "By Signature" tab or breakdown view',
          'Verify each signature is listed with its click/view counts',
          'Check that totals add up correctly',
        ],
      },
      {
        id: 'ana-6',
        description: 'Export analytics data to CSV',
        priority: 'P2',
        howTo: [
          'Go to the Analytics page',
          'Look for an "Export" or "Download CSV" button',
          'Click it and verify a CSV file downloads',
          'Open the CSV and verify it contains the analytics data shown on screen',
          'Check column headers are descriptive (date, user, signature, clicks, views, etc.)',
        ],
      },
    ],
  },
  {
    id: 'whitelabel',
    title: 'White-Label & Branding',
    steps: [
      {
        id: 'wl-1',
        description: 'MSP portal loads at custom subdomain',
        priority: 'P1',
        howTo: [
          'Prerequisite: An MSP partner org must be set up with a custom subdomain',
          'Open the custom subdomain URL in a browser (e.g., partner.siggly.com)',
          'Verify the page loads without errors',
          'Check that the MSP branding (logo, colors) is displayed, not Siggly branding',
        ],
        sampleData: {
          'Note': 'MSP subdomains must be configured in the admin panel first',
        },
      },
      {
        id: 'wl-2',
        description: 'Custom branding (logo, colors) applies to MSP portal',
        priority: 'P1',
        howTo: [
          'Log in as an MSP partner admin',
          'Go to Settings → Branding',
          'Upload a custom logo',
          'Set custom brand colors',
          'Save changes',
          'Visit the MSP portal URL and verify the custom branding appears',
          'Check login page, dashboard, and signature editor all show custom branding',
        ],
      },
      {
        id: 'wl-3',
        description: 'MSP can manage client organizations',
        priority: 'P1',
        howTo: [
          'Log in as an MSP partner admin',
          'Navigate to the client management or "Organizations" section',
          'Verify you can see a list of client organizations',
          'Try creating a new client org',
          'Verify you can view client org details (users, signatures, billing)',
        ],
      },
      {
        id: 'wl-4',
        description: 'MSP can deploy signatures for client users',
        priority: 'P1',
        howTo: [
          'Log in as an MSP partner admin',
          'Switch to or select a client organization',
          'Create or select a signature for a client user',
          'Deploy the signature via the available method (Google/Microsoft/Copy)',
          'Verify the deployment succeeds for the client org\'s users',
        ],
      },
      {
        id: 'wl-5',
        description: 'Client users see MSP branding, not Siggly branding',
        priority: 'P2',
        howTo: [
          'Log in as a user belonging to an MSP client organization',
          'Verify the dashboard shows the MSP\'s branding (logo, colors)',
          'Check that "Siggly" branding is NOT visible anywhere',
          'Navigate to multiple pages and verify branding is consistent',
        ],
      },
      {
        id: 'wl-6',
        description: 'MSP billing aggregates across all client orgs',
        priority: 'P2',
        howTo: [
          'Log in as an MSP partner admin',
          'Go to Billing or the partner billing section',
          'Verify you can see aggregated billing across all client orgs',
          'Check that the total seat count sums all client org users',
          'Verify individual client org billing breakdowns are visible',
        ],
      },
    ],
  },
];
